# Generated by Django 3.0.7 on 2020-07-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='slug',
            field=models.CharField(default=1, max_length=40, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hello',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
