# Generated by Django 3.0.7 on 2020-07-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200702_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='Url'),
        ),
    ]
