# Generated by Django 3.0.7 on 2020-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200702_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='url'),
        ),
    ]
